version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: sh -c "python3 manage.py collectstatic --noinput && python3 manage.py makemigrations && python3 manage.py migrate && gunicorn -c ./configs/gunicorn.py core.wsgi"

  nginx:
    image: nginx:alpine
    ports:
      - 8895:80
    volumes:
      - ./configs/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/www/data/staticfiles
      - ./media:/www/data/media
    depends_on:
      - web