version: '3.8'
services:
  django-app:
    container_name: django-app
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python3 manage.py collectstatic --noinput && python3 manage.py makemigrations && python3 manage.py migrate && gunicorn --config configs/gunicorn.py core.wsgi:application"
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - /var/www/static/:/var/www/static/
    env_file:
      - .env
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true