# Generated by Django 4.2.16 on 2025-01-09 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_aula_curso_modulo_delete_tipocurso_aula_modulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='aula',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='cursos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aula',
            name='tipo_conteudo',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('VIDEO', 'Vídeo'), ('ARQUIVO', 'Arquivo')], default='VIDEO', max_length=20),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado'), ('IMERSAO', 'Imersão')], default='PUBLICO', max_length=20),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='api.curso')),
            ],
        ),
        migrations.CreateModel(
            name='AulaConcluida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusoes', to=settings.AUTH_USER_MODEL)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusoes', to='api.aula')),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='aulas/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='api.aula')),
            ],
        ),
    ]
