# Generated by Django 4.2.16 on 2025-01-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_aula_arquivo_aula_video_curso_alunos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivoaula',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/'),
        ),
    ]
