# Generated by Django 4.2.16 on 2024-11-20 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_emblema', '0001_initial'),
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='complete_name',
            field=models.CharField(default='pedro cruz', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_emblema.instituicao'),
        ),
    ]
